// <auto-generated />
using System;
using GalaxyMusicDataset.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GalaxyMusicDataset.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.AggregationJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("StartedAt");

                    b.ToTable("AggregationJobs");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mbid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mbid")
                        .IsUnique();

                    b.HasIndex("ArtistId", "Title");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.ApiRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("Source");

                    b.ToTable("ApiRequestLogs");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Artist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFmUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mbid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mbid")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.ArtistAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locale")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId", "Name")
                        .IsUnique();

                    b.ToTable("ArtistAliases");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Scrobble", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastFmAlbumMbid")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFmArtistMbid")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFmTrackMbid")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalAlbum")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalArtist")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixTimestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("TrackId");

                    b.HasIndex("UnixTimestamp")
                        .IsUnique();

                    b.ToTable("Scrobbles");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AccountRegisteredUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("BackfillCursorDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackfillDaysCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnrichmentPaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncrementalRuns")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBackfillComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastFmPlaycount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastFmUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NewestUnix")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OldestUnix")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackfillDaysCompleted = 0,
                            EnrichmentPaused = false,
                            IncrementalRuns = 0,
                            IsBackfillComplete = false
                        });
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Track", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mbid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("Mbid")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.TrackLookup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BestScore")
                        .HasColumnType("REAL");

                    b.Property<string>("CandidateJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedMbid")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryUsed")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackLookups");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.TrackSourcePayload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "Source")
                        .IsUnique();

                    b.ToTable("TrackSourcePayloads");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.TrackTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("TrackId", "TagId", "Source")
                        .IsUnique();

                    b.ToTable("TrackTags");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Album", b =>
                {
                    b.HasOne("GalaxyMusicDataset.Data.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.ArtistAlias", b =>
                {
                    b.HasOne("GalaxyMusicDataset.Data.Entities.Artist", "Artist")
                        .WithMany("Aliases")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Scrobble", b =>
                {
                    b.HasOne("GalaxyMusicDataset.Data.Entities.Track", "Track")
                        .WithMany("Scrobbles")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Track", b =>
                {
                    b.HasOne("GalaxyMusicDataset.Data.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GalaxyMusicDataset.Data.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.TrackLookup", b =>
                {
                    b.HasOne("GalaxyMusicDataset.Data.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Track");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.TrackSourcePayload", b =>
                {
                    b.HasOne("GalaxyMusicDataset.Data.Entities.Track", "Track")
                        .WithMany("SourcePayloads")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.TrackTag", b =>
                {
                    b.HasOne("GalaxyMusicDataset.Data.Entities.Tag", "Tag")
                        .WithMany("TrackTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalaxyMusicDataset.Data.Entities.Track", "Track")
                        .WithMany("Tags")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Aliases");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Tag", b =>
                {
                    b.Navigation("TrackTags");
                });

            modelBuilder.Entity("GalaxyMusicDataset.Data.Entities.Track", b =>
                {
                    b.Navigation("Scrobbles");

                    b.Navigation("SourcePayloads");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
